#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);


#--------------------------------------------------
# actions for nethserver-collectd-update event
#--------------------------------------------------

my $event = "nethserver-collectd-update";

event_actions($event,
              'initialize-default-databases' => '00',
              'nethserver-collectd-conf' => '02',
              'runlevel-adjust' => '40');
templates2events("/etc/collectd.conf",  $event);
event_services($event, 'collectd' => 'restart');


#--------------------------------------------------
# actions for nethserver-collectd-save event
#--------------------------------------------------

$event = "nethserver-collectd-save";

templates2events("/etc/collectd.conf",  $event);
event_services($event, 'collectd' => 'restart');


#--------------------------------------------------
# actions for nethserver-collectd-uninstall event
#--------------------------------------------------

$event = "nethserver-collectd-uninstall";

event_actions($event,
              'nethserver-collectd-uninstall' => '02',
              'runlevel-adjust' => '50');

exit;
